"""add spending categories and merchant categories

Revision ID: 41d32d74dbcb
Revises: 340264729e5d
Create Date: 2026-07-14 17:07:50.972900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41d32d74dbcb'
down_revision: Union[str, Sequence[str], None] = '340264729e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spending_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['spending_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spending_categories_code'), 'spending_categories', ['code'], unique=True)
    op.create_index(op.f('ix_spending_categories_id'), 'spending_categories', ['id'], unique=False)
    op.create_table('merchant_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('mcc', sa.String(length=10), nullable=True),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['spending_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_categories_id'), 'merchant_categories', ['id'], unique=False)
    op.create_index(op.f('ix_merchant_categories_mcc'), 'merchant_categories', ['mcc'], unique=False)
    op.create_index(op.f('ix_merchant_categories_merchant_name'), 'merchant_categories', ['merchant_name'], unique=False)
    op.create_index(op.f('ix_merchant_categories_normalized_name'), 'merchant_categories', ['normalized_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_merchant_categories_normalized_name'), table_name='merchant_categories')
    op.drop_index(op.f('ix_merchant_categories_merchant_name'), table_name='merchant_categories')
    op.drop_index(op.f('ix_merchant_categories_mcc'), table_name='merchant_categories')
    op.drop_index(op.f('ix_merchant_categories_id'), table_name='merchant_categories')
    op.drop_table('merchant_categories')
    op.drop_index(op.f('ix_spending_categories_id'), table_name='spending_categories')
    op.drop_index(op.f('ix_spending_categories_code'), table_name='spending_categories')
    op.drop_table('spending_categories')
    # ### end Alembic commands ###
