"""add financial memory events

Revision ID: a4718b2b33cc
Revises: f23b64993c90
Create Date: 2026-07-15 14:59:59.179114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4718b2b33cc'
down_revision: Union[str, Sequence[str], None] = 'f23b64993c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detection_source', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_events_id'), 'financial_events', ['id'], unique=False)
    op.create_index(op.f('ix_financial_events_user_id'), 'financial_events', ['user_id'], unique=False)
    op.create_table('financial_event_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['financial_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_event_transactions_event_id'), 'financial_event_transactions', ['event_id'], unique=False)
    op.create_index(op.f('ix_financial_event_transactions_transaction_id'), 'financial_event_transactions', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financial_event_transactions_transaction_id'), table_name='financial_event_transactions')
    op.drop_index(op.f('ix_financial_event_transactions_event_id'), table_name='financial_event_transactions')
    op.drop_table('financial_event_transactions')
    op.drop_index(op.f('ix_financial_events_user_id'), table_name='financial_events')
    op.drop_index(op.f('ix_financial_events_id'), table_name='financial_events')
    op.drop_table('financial_events')
    # ### end Alembic commands ###
