"""add transaction ai analysis

Revision ID: f23b64993c90
Revises: 41d32d74dbcb
Create Date: 2026-07-15 13:11:49.988107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23b64993c90'
down_revision: Union[str, Sequence[str], None] = '41d32d74dbcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_ai_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('merchant_category_id', sa.Integer(), nullable=True),
    sa.Column('spending_category_id', sa.Integer(), nullable=False),
    sa.Column('normalized_merchant', sa.String(length=250), nullable=False),
    sa.Column('display_merchant_name', sa.String(length=250), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('category_code', sa.String(length=100), nullable=False),
    sa.Column('parent_category', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('classification_source', sa.String(length=50), nullable=False),
    sa.Column('classification_reason', sa.Text(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('is_subscription', sa.Boolean(), nullable=False),
    sa.Column('is_business', sa.Boolean(), nullable=True),
    sa.Column('essentiality', sa.String(length=30), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_category_id'], ['merchant_categories.id'], ),
    sa.ForeignKeyConstraint(['spending_category_id'], ['spending_categories.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_ai_analysis_id'), 'transaction_ai_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_ai_analysis_transaction_id'), 'transaction_ai_analysis', ['transaction_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_ai_analysis_transaction_id'), table_name='transaction_ai_analysis')
    op.drop_index(op.f('ix_transaction_ai_analysis_id'), table_name='transaction_ai_analysis')
    op.drop_table('transaction_ai_analysis')
    # ### end Alembic commands ###
